spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8181
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://hecheng-pc1:8081/eureka/,http://hecheng-pc2:8082/eureka/,http://hecheng-pc3:8083/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8182